development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://rnmlepeywomuzc:xtAAjF0rKe2eqASxbu46Ozohlo@ec2-54-243-203-232.compute-1.amazonaws.com:5432/db7jhsp6rsdgnd
